#ifndef HEADER_WIFI_STATION_MODE_MODULE
#define HEADER_WIFI_STATION_MODE_MODULE

/* Wi-fi security configurations */
#if CONFIG_ESP_WIFI_AUTH_OPEN
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_OPEN
#elif CONFIG_ESP_WIFI_AUTH_WEP
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WEP
#elif CONFIG_ESP_WIFI_AUTH_WPA_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA2_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA_WPA2_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_WPA2_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA3_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA3_PSK
#elif CONFIG_ESP_WIFI_AUTH_WPA2_WPA3_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_WPA3_PSK
#elif CONFIG_ESP_WIFI_AUTH_WAPI_PSK
#define WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WAPI_PSK
#endif

/* Wi-Fi credentials */
#define WIFI_SSID_ST_DEFAULT           "YOUR_SSID"
#define WIFI_PASS_ST_DEFAULT           "YOUR_PASSWORD"
#define WIFI_ST_GATEWAY                "192.168.0.1"
#define WIFI_ST_NETWORK_MASK           "255.255.255.0"
#define MAX_SIZE_SSID_WIFI_ST           32
#define MAX_SIZE_PASS_WIFI_ST           64
#define MAX_SIZE_GATEWAY_IP             16
#define MAX_SIZE_GATEWAY_MASK           16

#endif

/* Protótipos */
void wifi_init_sta_st(void);
bool get_wifi_connection_status(void);